[tools]
java = "17"
gradle = "8.9"
just = "latest"
flutter = "latest"
bun = "1.1.0"
node = "20"

[env]
# Ensure mise tools are in PATH
_.path = ["{{config_root}}/node_modules/.bin"]

[settings]
# Experimental features
experimental = true
