packages:
  - apps/*
  - packages/*
  - tooling/*

# Shared dependency versions
catalog:
  "typescript": "^5.6.3"
  "@types/node": "^22.9.0"
  "eslint": "^9.14.0"
  "prettier": "^3.3.3"
  "turbo": "^2.3.3"
  "zod": "^3.23.8"

# React catalog for webapp
catalogs:
  react19:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "@types/react": "^19.0.0"
    "@types/react-dom": "^19.0.0"

# Build optimizations
onlyBuiltDependencies:
  - esbuild
  - sharp

# Workspace linking
nodeLinker: hoisted
linkWorkspacePackages: true

# Ensure consistent package resolution
resolution-mode: highest

# Override any problematic dependency versions
overrides:
  "@types/minimatch": "5.1.2"