packages:
  - apps/*
  - packages/*
  - tooling/*

# Shared dependency versions
catalog:
  "typescript": "^5.6.3"
  "@types/node": "^22.9.0"
  "eslint": "^9.14.0"
  "prettier": "^3.3.3"
  "zod": "^3.23.8"

# Build optimizations
onlyBuiltDependencies:
  - esbuild
  - sharp

# Workspace linking
nodeLinker: hoisted
linkWorkspacePackages: true

# Ensure consistent package resolution across workspace
# Using 'highest' to prefer latest compatible versions within semver ranges
resolution-mode: highest

# Override any problematic dependency versions
overrides:
  "@types/minimatch": "5.1.2"