name: MealPlanner
options:
  bundleIdPrefix: com.mealplanner
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    SWIFT_VERSION: 5.9
packages: {}
targets:
  MealPlanner:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
      - path: Resources
        type: resources
        excludes:
          - "webapp/**"
      - path: Assets.xcassets
        type: assets
      - path: Resources/webapp
        type: folder
        buildPhase: resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mealplanner.app
      INFOPLIST_FILE: Resources/Info.plist
